version: '3'
services:

###--- Lychee Setup ---###
   lychee:
     container_name: lychee
     image: linuxserver/lychee:latest
#     env_file:
#       - ./secrets.env
     volumes:
       - /opt/appdata/lychee/config:/config
#        - lychee_pictures:/pictures
#        - /mnt/lychee:/pictures
       - pictures:/pictures
       - /etc/localtime:/etc/localtime:ro
     restart: always
     environment:
       PUID: 1000
       PGID: 1000
       TZ: American/Los_Angeles
     labels:
       traefik.enable: "true"
       traefik.frontend.redirect.entryPoint: "https"
       traefik.frontend.rule: "Host:lychee.wooster.xyz"
       traefik.port: "80"
       traefik.docker.network: "plexguide"
     ports:
       - 9413:80
     networks:
       - plexguide

###--- MariaDb Setup ---###
   mariadb_lychee:
     container_name: mariadb_lychee
     image: mariadb
     env_file:
       - ./secrets.env
     volumes:
       - /opt/appdata/mariadb_lychee/lib/mysql:/var/lib/mysql
       - /etc/localtime:/etc/localtime:ro
     restart: always
     environment:
#       MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
       MYSQL_DATABASE: "lychee"
#       MYSQL_USER: ${USER}
#       MYSQL_PASSWORD: ${USER_PASSWORD}
     networks:
       - plexguide

volumes:
  pictures:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.46.119.45,rw"
      device: ":/export/media"

networks:
  plexguide:
    external:
      name: plexguide
